### ISSUE TITLE
Если в checkbox в филдсетах?

### ISSUE THREAD

**Issue by Bogdan808** [flextype/flextype#272]
Добрый день, использую вашу cms.
Возник вопрос:
Можно ли использовать в записях чекбокс?
Спасибо

**Comment by Awilum** [comment]
@Bogdan808 Доброго времени суток!
чекбоксов пока нет, но возможность выбора можно реализовать с помощью **select**

пример:

```
      menu_item_target:
        title: admin_menu_item_target
        type: select
        options: { _self: _self, _blank: _blank, _parent: _parent, _top: _top }
        size: 4/12
```
