### ISSUE TITLE
Flextype Core: add routable option for entries

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#284]
We should able to set custom **routable** option for all entries.

Logic: 
if **routable** is **true** for requested entry, then it is reachable by URL else we should not provide this entry by URL

**Comment by Awilum** [comment]
implemented 

usage:

```

      routable:
        title: admin_routable
        type: routable_select
        size: 4/12
```
