### ISSUE TITLE
Flextype Core: add query functionality for fieldsets 

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#285]
We should have **query functionality** for fieldsets. 
This will allow us to populate form controls values with data fetched from different sources.

for e.g.

```
title:
  title: Title
  type: text
  value: query
  query: registry.settings.title
```
