### ISSUE TITLE
 Flextype Core: Forms - add new heading field 

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#299]

**Comment by Awilum** [comment]
implemented 

usage:

```
    fields:
      general_heading:
        title: admin_general
        type: heading
        h: 1
```
