### ISSUE TITLE
Flextype Core: Forms - add new routable_select field

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#300]

**Comment by Awilum** [comment]
implemented

usage:

```
      routable:
        title: admin_routable
        type: routable_select
        size: 4/12
```
