### ISSUE TITLE
Flextype Core: Decouple settings for system plugins from the engine core.

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#368]
Decouple settings for system plugins from the engine core.

BREAKING CHANGE:

this settings will be stored in the **registry.plugin.site.***

```

# The title of the website
title: Flextype

# The description of the website
description: Build fast, flexible, easier to manage websites with Flextype.

# The keywords of the website
keywords: flextype, php, cms, flat-file cms, flat cms, flatfile cms, html

# The robots of the website
robots: index, follow

# The name and email address of the website author
author:
  email: ''
  name: ''
```

this settings will be stored in the **registry.plugin.admin.***

```

# entries settings
entries:
  items_view_default: list
  media:
    upload_images_quality: 70
    upload_images_width: 1600
    upload_images_height: 0
    accept_file_types: gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg
```
