### ISSUE TITLE
Flextype Core: add Serializer for data encoding/decoding. 

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#424]
We should have **Serializer** for data encoding/decoding and **Parser** for data parsing into html format.

Serializer:
- JSON
- Yaml
- Frontmatter

Parser: 
- Markdown
- Shortcodes

Parsers should works optionally, for all fields or just only for content field
something like this: 
```
parsers:
  markdown:
    enabled: true
    cache: true
    fields: ['fileld1', 'field2']
  shortcodes:
    enabled: true
    cache: false
    fields: "*"
```
