### ISSUE TITLE
Move to PhpFastCache

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#457]
I am researching question to use **PhpFastCache** (by @Geolim4) instead of **Doctrine Cache**.
Seems that Doctrine Cache is lacking with updates and looks legacy. 
No updates, PR and issues really old and seems not to be resolved at all.

**PhpFastCache** is much more modern and it is keep updating!
https://github.com/PHPSocialNetwork/phpfastcache

**Comment by Geolim4** [comment]
Hello,

Also please note that Phpfastcache provide a PSR16 adapter and a strong configuration mechanism along with a [well-documented WIKI](https://github.com/PHPSocialNetwork/phpfastcache/wiki).

Be aware that the latest version (v8) is only php 7.3+ compatible, however the V7 is php 7.0+ compatible, with strict types enforced 👍 

Happy caching !

**Comment by Geolim4** [comment]
Anyway if you have any questions,

Feel free to contact me ;)

**Comment by Awilum** [comment]
@Geolim4 Thanks! 
Flextype project will go with PHP 7.3 in upcoming release. ;)

**Comment by Awilum** [comment]
**New config for PhpFastCache**

```
cache:
  enabled: true
  driver: sqlite
  drivers:
    apcu: {}
    cassandra:
      host: '127.0.0.1'
      port: 9042
      timeout: 2
      username: ''
      password: ''
      ssl_enabled: false
      ssl_verify: false
      default_ttl: 900
    cookie:
      aware_of_untrustable_data: false
      limited_memory_by_object: 4096
      default_ttl: 900
    couchbase:
      host: '127.0.0.1'
      port: 8091
      username: ''
      password: ''
      bucket_name: default
      default_ttl: 900
    couchdb:
      database: 'flextype'
      path: '/'
      host: '127.0.0.1'
      port: 8091
      username: ''
      password: ''
      bucket_name: default
      ssl: false
      timeout: 10
      default_ttl: 900
    devnull: {}
    devfalse: {}
    devtrue: {}
    files:
      path: /tmp
      security_key: 'auto'
      htaccess: true
      secure_file_manipulation: false
      cache_file_extension: txt
      default_ttl: 900
    leveldb:
      path: /tmp
      security_key: 'auto'
      htaccess: true
      default_ttl: 900
    memcache:
      host: '127.0.0.1'
      port: 11211
      sasl_user: ''
      sasl_password: ''
      path: '/'
      compress_data: false
      servers: {}
      default_ttl: 900
    memcached:
      host: '127.0.0.1'
      port: 11211
      sasl_user: ''
      sasl_password: ''
      path: '/'
      compress_data: false
      servers: {}
      default_ttl: 900
    memstatic: {}
    mongodb:
      host: '127.0.0.1'
      port: 27017
      username: ''
      password: ''
      timeout: 3
      servers: {}
      collection_name: 'Cache'
      default_ttl: 900
    predis:
      host: '127.0.0.1'
      port: 6379
      password: ''
      timeout: 5
      database: 0
      opt_prefix: ''
      persistent: false
      default_ttl: 900
    redis:
      host: '127.0.0.1'
      port: 6379
      password: ''
      timeout: 5
      database: 0
      opt_prefix: ''
      default_ttl: 900
    riak:
      host: '127.0.0.1'
      port: 8098
      prefix: 'riak'
      default_ttl: 900
    sqlite:
      path: /tmp
      security_key: auto
      htaccess: true
      default_ttl: 900
    ssdb:
      host: 127.0.0.1
      port: 8888
      password: ''
      timeout: 5
    wincache: {}
    xcache: {}
    zenddisk: {}
    zendshm: {}
```

**New methods from PhpFastCache**
We are start using PhpFastCache PSR16 adapter 
https://github.com/PHPSocialNetwork/phpfastcache

**BREAKING CHANGES** 
- old cache config removed, use new config for PhpFastCache 
- use methods `has()` `set()` `get()` instead of `contains()` `save()` `fetch()`
