### ISSUE TITLE
Add markdown basic settings 

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#471]
We should have basic settings for markdown parser

```
markdown:
  auto_line_breaks: false
  auto_url_links: false
  escape_markup: false
```

https://github.com/erusev/parsedown
