### ISSUE TITLE
 Add new field `entries.fetchSingle` and `entries.fetchCollection` for Entries API

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#492]
Entries API provides two methods for entries fetch: `fetchCollection()` and `fetchSingle()` and we should able to access them inside entries frontmatter header for fetching data right in the entries. Also, we will able to add and use any kind of fetch methods with our macroable functionality. 

### Basic Example

Catalog entry with several queries and with several nested queries inside of children entries.

File: `/project/entries/catalog/entry.md`

```yaml
---
title: Catalog
visibility: visible
entries:
  fetchSingle:
    label1:
      id: discounts/50-off
      options:
        filter:
          limit: 4
  fetchCollection:
    bikes:
      id: catalog/bikes
      options:
        filter:
          where:
            -
              key: brand
              operator: eq
              value: gt
          limit: 10
    discounts:
      id: discounts
      options:
        filter:
          where:
            -
              key: title
              operator: eq
              value: '30% off'
            -
              key: category
              operator: eq
              value: bikes
---
```

**JSON Result**

```json
 {
  "title": "Catalog",
  "visibility": "visible",
  "entries": {
    "fetchSingle": {
      "label1": {
        "id": "discounts/50-off",
        "options": { "filter": { "limit": 4 } }
      }
    },
    "fetchCollection": {
      "bikes": {
        "id": "catalog/bikes",
        "options": {
          "filter": {
            "where": [{ "key": "brand", "operator": "eq", "value": "gt" }],
            "limit": 10
          }
        }
      },
      "discounts": {
        "id": "discounts",
        "options": {
          "filter": {
            "where": [
              { "key": "title", "operator": "eq", "value": "30% off" },
              { "key": "category", "operator": "eq", "value": "bikes" }
            ]
          }
        }
      }
    }
  },
  "published_at": 1607980440,
  "published_by": "",
  "created_at": 1607980440,
  "created_by": "",
  "routable": true,
  "uuid": "a442be0c-1d02-4ddc-b42c-d77f8b000d84",
  "content": "",
  "bikes": {
    "catalog/bikes/gt": {
      "title": "GT",
      "brand": "gt",
      "entries": {
        "fetchCollection": {
          "discounts_available": {
            "id": "discounts",
            "options": {
              "filter": {
                "where": [
                  { "key": "category", "operator": "eq", "value": "bikes" }
                ]
              }
            }
          }
        },
        "fetchSingle": {
          "label1": {
            "id": "discounts/50-off",
            "options": { "filter": { "limit": 3 } }
          },
          "label2": {
            "id": "discounts/30-off",
            "options": { "filter": { "limit": 2 } }
          }
        }
      },
      "published_at": 1607980440,
      "published_by": "",
      "created_at": 1607980440,
      "created_by": "",
      "routable": true,
      "visibility": "visible",
      "uuid": "8c6c8f5d-191c-4a44-b844-39588c1d8612",
      "content": "",
      "discounts_available": {
        "discounts/50-off": {
          "title": "50% off",
          "category": "bikes",
          "published_at": 1607980440,
          "published_by": "",
          "created_at": 1607980440,
          "created_by": "",
          "routable": true,
          "visibility": "visible",
          "uuid": "818626f0-2d6a-4e23-8ad8-bff3015e259f",
          "content": "",
          "slug": "discounts/50-off",
          "modified_at": 1607980471,
          "id": "discounts/50-off"
        },
        "discounts/30-off": {
          "title": "30% off",
          "category": "bikes",
          "published_at": 1607980440,
          "published_by": "",
          "created_at": 1607980440,
          "created_by": "",
          "routable": true,
          "visibility": "visible",
          "uuid": "5b4a993c-e924-49aa-8af8-370f2fcd9616",
          "content": "",
          "slug": "discounts/30-off",
          "modified_at": 1607980471,
          "id": "discounts/30-off"
        }
      },
      "label1": {
        "title": "50% off",
        "category": "bikes",
        "published_at": 1607980440
      },
      "label2": { "title": "30% off", "category": "bikes" },
      "slug": "catalog/bikes/gt",
      "modified_at": 1607980471,
      "id": "catalog/bikes/gt"
    }
  },
  "discounts": {
    "discounts/30-off": {
      "title": "30% off",
      "category": "bikes",
      "published_at": 1607980440,
      "published_by": "",
      "created_at": 1607980440,
      "created_by": "",
      "routable": true,
      "visibility": "visible",
      "uuid": "5b4a993c-e924-49aa-8af8-370f2fcd9616",
      "content": "",
      "slug": "discounts/30-off",
      "modified_at": 1607980471,
      "id": "discounts/30-off"
    }
  },
  "label1": {
    "title": "50% off",
    "category": "bikes",
    "published_at": 1607980440,
    "published_by": ""
  },
  "slug": "catalog",
  "modified_at": 1607980471,
  "id": "catalog"
}
```

### Setting for this fields

File: `/project/config/flextype/settings.yaml`

```yaml
entries:
  fields:
    entries:
      fetchCollection:
        enabled: true
        result: toObject
      fetchSingle:
        enabled: true
        result: toObject
```

Valid values for setting **enabled** is **true** or **false** 
Valid values for setting **result** is **toObject** or **toArray**
