### ISSUE TITLE
Reorganize endpoints for Media Rest API

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#514]
We should have all media endpoints inside the **/media/** api url.

**BREAKING CHANGES**

|  | NEW ENDPOINT | OLD ENDPOINT | 
|---|---|---|
| **GET** |  /api/media/files |  /api/files |
| **POST** |  /api/media/files |  /api/files |
| **PUT** |  /api/media/files |  /api/files |
| **PATCH** |  /api/media/files |  /api/files |
| **DELETE** |  /api/media/files |  /api/files |
| **POST** |  /api/media/files/copy |  /api/files/copy |
| **PATCH** |  /api/media/files/meta |  /api/files/meta |
| **POST** |  /api/media/files/meta |  /api/files/meta |
| **DELETE** |  /api/media/files/meta |  /api/files/meta |
| **GET** |  /api/media/folders |  /api/folders |
| **POST** |  /api/media/folders |  /api/folders |
| **PATCH** |  /api/media/folders |  /api/folders |
| **DELETE** |  /api/media/folders |  /api/folders |
| **POST** |  /api/media/folders/copy |  /api/folders/copy |

**Tokens:**
- token for files should be moved from `/tokens/files/` to `/tokens/media/files/`
- token for folders should be moved from `/tokens/folders/` to `/tokens/media/folders/`

**Settings:**
```yaml
api:
  ...
  media:
    files:
      enabled: true
      default_token:
    folders:
      enabled: true
      default_token:
```
