### ISSUE TITLE
Parsers: move markdown and shortcode settings under parsers setting.

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#539]
Updated settings.yaml 

 ```yaml
parsers:
  markdown:
    auto_line_breaks: false
    auto_url_links: false
    escape_markup: false
  shortcode:
    shortcodes:
      entries:
        enabled: true
      raw:
        enabled: true
      registry:
        enabled: true
      url:
        enabled: true
```
