### ISSUE TITLE
Media: move images settings into media.images settings

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#541]
updated section in setting.yaml

```yaml 
media:
  accept_file_types: 'gif, jpg, jpeg, png, ico, zip, tgz, txt, md, doc, docx, pdf, epub, xls, xlsx, ppt, pptx, mp3, ogg, wav, m4a, mp4, m4v, ogv, wmv, avi, webm, svg'
  max_file_size: 8000000
  safe_names: true
  images:
    driver: gd
    image_width: 1600
    image_height: 0
    image_quality: 70
    max_image_width: null
    max_image_height: null
```
