### ISSUE TITLE
Entries Fields Operators

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#579]
We should have: entries fields operators. 
This feature will allow us to get data from anywhere and assign the result for a specific field.

```yaml
field1: _registry.get
field2: _entries.fetch
field2: _random.string

etc...
```
