### ISSUE TITLE
Improve Entries Expression

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#582]
Currently entries expression allows to use `fetch`, `has` and `registry` methods.
We should able to use methods `create`, `update`, `delete`, `copy` and `move`.
Methods access should configurable.

Settings:

```yaml
...
  ...
      fetch:
        enabled: true
      has:
        enabled: true
      registry:
        enabled: true
      create:
        enabled: false
      move:
        enabled: false
      update:
        enabled: false
      delete:
        enabled: false
``` 

Examples of usage:

```yaml
create: '[[ entries().create("foo") ]]'
fetch: '[[ entries().fetch("foo").get("title") ]]'
has: '[[ entries().has("foo") ]]'
delete: '[[ entries().delete("foo") ]]'
copy: '[[ entries().copy("copy-foo", "copy-foo-2") ]]'
move: '[[ entries().move("move-foo", "move-foo-2") ]]'
update: '[[ entries().update("update-foo", {"title": "Foo"}) ]]'
registry: '[[ entries().registry().get("methods.fetch.id") ]]'
```
