### ISSUE TITLE
Add ability to define global vars

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#584]
We should have an API to define global vars.

Example:

plugin.php
```php
vars()->set('message', 'lorem');
```

blog/post-1.md
```yaml
---
title: Post 1
message: "[[ vars().get('message') ]]"
---
```

blog/post-2.md
```yaml
---
title: Post 2
message: "[[ var('message') ]]"
---
```

The idea is to share variables with all entries globally.
