### ISSUE TITLE
Add private fields functionality for entries

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#585]
We should have private fields for entries. 
They should be available only inside the current entry.

Private field starts with **_**

Example of usage:

**entry.md**
```yaml
---
title: Product item
_message: Message...
_vars:
  currency: "USD"
  vat: "@type[int] [[ strings().random(2, 1234567890) ]]"
price: "[[ 100 + _vars.vat ]]"
price_with_currency: "[[ price ~ ' ' ~ _vars.currency ]]"
---

[[ title ]] // Product item

[[ _message ]] // Message...
```

**Response**
```json
{
    "title": "Product item",
    "price": "120",
    "price_with_currency": "120 USD"
    "content": "Product item \n Message..."
}
```
