### ISSUE TITLE
Expressions language as a part of Parsers

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#586]
Expressions should be part of Parsers, configurable and available globally.

**ADD**

* Ability to configure opening/closing tags for variables, blocks and comments
```yaml
    opening_variable_tag: "[["
    closing_variable_tag: "]]"
    opening_block_tag: "[%"
    closing_block_tag: "%]"
    opening_comment_tag: "[#"
    closing_comment_tag: "#]"
```
* Ability to write multiline expressions 
```
[[ 
  field1 ~
  field2 ~
  field2
]]
```
* Ability to store parsed expressions in the cache
* Ability to quickly access current entries fields

**BREAKING CHANGES**

- Configuration for expressions moved from entries to parsers section.
- Use `parsers()->expressions()` instead of `expressions()` to access methods.
