### ISSUE TITLE
Add ability to import and export entries

### ISSUE THREAD

**Issue by Awilum** [flextype/flextype#588]
We should have ability to import and export entries from files.

New Entries methods:
```php
/**
 * Import.
 * 
 * @param string $file File with data to import.
 */
public function import(string $file): bool

/**
 * Export.
 * 
 * @param string $id Entries ID to fetch data and export to file.
 * @param array $options Export options.
 */
public function export(string $id, array $options = []): bool
```

New console commands:
```
entries:export
entries:import
```

New settings:
```yaml
...
entries:
  ...
  export: 
    path: "_export"
    filename: ""
    serializer: "json"
  ...
...
```

Updated settings (added default extension):
```yaml
...
serializers:
  json: 
    extension: "json"
  json5: 
    extension: "yaml"
  yaml: 
    extension: "json5"
  neon: 
    extension: "neon"
  frontmatter: 
    extension: "md"
  phparray: 
    extension: "php"
...
```
